/*
    Most code from this file is taken and/or referenced from "Production Sky Rendering" at https://www.shadertoy.com/view/slSXRW,
    which is an implementation of "A Scalable and Production Ready Sky and Atmosphere Rendering Technique", Hillaire (2020).

    Minimal code changes; modified for my use case. The original shadertoy code was released under the MIT License.
*/

static const float groundRadiusMM = 6.360;